### ISSUE TITLE
Add "Generate & Copy" button

### ISSUE THREAD

**Issue by kutsan** [Engineering-Robert/lorem-ipsum-generator#1]
I like the project but one feature I want to have it that is generating and copying text at the same time. I certainly need to copy it so it should make sense to implement that.

**Comment by robertcoopercode** [comment]
Thanks for posting the issues. There is a "Copy" button that appears once the paragraphs have been generated. Are you proposing an additional button that Generates and Copies the text simultaneously?

**Comment by kutsan** [comment]
Yes, exactly. It would be better in my opinion.

**Comment by robertcoopercode** [comment]
I'm going to be leaving it as just a "generate" and "copy" button because I don't want a user to have to copy the text to their clipboard if they don't want to. The user might already be saving something to their clipboard that they want to use and it could be inconvenient for them to have that removed.

**Comment by kutsan** [comment]
I understand. One solution is; you could add an extra button next to that "Generate" button. Two buttons, one of them "Generate" other is "Generate & Copy".

In the term of UX, your thoughts are not practical. If the one want some dummy text, they shouldn't already have sensitive informations in their clipboard. They are gonna copy some text, that's why they searched and entered a Lorem Ipsum website in the first place. Without that button, they will still copy something.

Thanks for spending your time to answering. If it's not convenient enough, I am okay with that.
