### ISSUE TITLE
Add "Lorem ipsum dolor sit amet." text to the first paragraph of the text

### ISSUE THREAD

**Issue by kutsan** [Engineering-Robert/lorem-ipsum-generator#2]
Starting the dummy text with "Lorem ipsum dolor sit amet." sentence kind of standard way to do that even the following texts are not Latin. Especially customers will not confuse about that since they know it's dummy and will be replaced with actually content.

**Comment by robertcoopercode** [comment]
I can add this as an option. Thanks for the suggestion.

**Comment by robertcoopercode** [comment]
I'm not going to end up adding this since I want to keep the UI clean.
